CREATE DATABASE IF NOT EXISTS CASTELLO_RELACIONAMENTOS;

USE CASTELLO_RELACIONAMENTOS;

CREATE TABLE IF NOT EXISTS CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDOS (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    DATA_PEDIDO DATE NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS ESTOQUE (
    ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL UNIQUE,
    QUANTIDADE INT NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL
);

SELECT * FROM ESTOQUE;

INSERT INTO PRODUTOS (NOME_PRODUTO, PRECO) VALUES
('Produtos A', 10.00),
('Produtos B', 20.00),
('Produtos C', 30.00);




--- DESAFIOS ---

--- QUESTÃO 1 ---
--- CATEGORIA --- POSSUI --- PRODUTOS ---
--- (1,1                     1,N) ---


--- QUESTÃO 2 ---
--- FUNCIONARIO --- REGISTRA --- PEDIDOS ---
--- (1,1                         1,N) ---


--- QUESTÃO 3 ---
--- FORNECEDOR --- COMERCIALIZA --- PRODUTOS ---
--- (1,N                            1,N) ---


--- QUESTÃO 4 ---
--- CLIENTE --- RESERVA --- MESA
--- (1,1                    0,N)


--- QUESTÃO 5 ---
--- PESISO --- POSSUI --- ITENS ---
--- (1, N                 1,1)