-- COMANDOS PARA CRIAR BCD
CREATE DATABASE ACADEMIA_BEATRIZ;
CREATE DATABASE IF NOT EXISTS ACADEMIA_BEATRIZ;

-- COMANDO PARA APAGAR BCD
DROP DATABASE ACADEMIA_BEATRIZ;

-- COMANDO CRIAR TABELA
CREATE TABLE CLIENTES(
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY, 
CPF VARCHAR(14) NOT NULL UNIQUE,
NOME VARCHAR(60) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
ENDERECO VARCHAR(100),
DATA_NASCIMENTO DATE NOT NULL,
STATUS_CLIENTE ENUM ('PENDENTE', 'ATIVO', 'INATIVO') DEFAULT "ATIVO",
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FUNCIONARIOS (
ID_FUNCIONARIOS INT PRIMARY KEY,
EMAIL VARCHAR(255) UNIQUE
);

CREATE TABLE PLANO (
ID_PLANO INT AUTO_INCREMENT PRIMARY KEY,
TIPO_PLANO VARCHAR(15) NOT NULL,
VALOR_PLANO DECIMAL (5,2) DEFAULT 0.00,
ADICIONAIS CHAR (10) DEFAULT "EXAME",
OBSERVACAO TEXT
);

-- COMANDO PARA ALTERAR E CORRIGIR
ALTER TABLE CLIENTES ADD EMAIL VARCHAR(100);

-- INSERIR DADOS NA BCD
INSERT INTO CLIENTES (ID_CLIENTES, NOME, CPF, TELEFONE, ENDERECO, DATA_NASCIMENTO, STATUS_CLIENTE, DATA_CADASTRO)
VALUES ('', 'BEATRIZ', '241.665.058-07', '(19) 99243-5672', 'RUA OLAVO FERREIRA', '07/10/2009', 'ATIVO', '');

INSERT INTO FUNCIONARIOS (ID_FUNCIONARIOS, EMAIL)
VALUES (1, 'BEATRIZBARROS@SENAI.COM.BR');

-- COMANDO PARA CONSULTAR INFORMAÇÕES NA TABELA
SELECT * FROM FUNCIONARIOS;

-- VIZUALIZAR TABELAS NO BCD
SHOW TABLES;

-- MODIFICAR TIPO DE DADOS OU CAMPOS
ALTER TABLE CLIENTES MODIFY EMAIL VARCHAR (150);

-- EXCLUIR ATRIBUTO
ALTER TABLE CLIENTES DROP COLUMN EMAIL;

-- LIMPAR DADOS DA TABELA
TRUNCATE TABLE CLIENTES;

-- COMANDO PARA ATIVAR BCD
USE ACADEMIA_BEATRIZ
