-- PROJETO SMARTCOFFEE

CREATE DATABASE SMARTCOFFEE_BEATRIZ;
CREATE DATABASE IF NOT EXISTS SMARTCOFFEE_BEATRIZ;

CREATE TABLE CLIENTES(
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY, 
CPF VARCHAR(14),
NOME VARCHAR(60),
TELEFONE VARCHAR(15),
DATA_NASCIMENTO DATE NOT NULL,
STATUS_CLIENTE ENUM ('PENDENTE', 'ATIVO', 'INATIVO') DEFAULT "ATIVO",
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PEDIDOS (
ID_PEDIDOS INT PRIMARY KEY,




);



 USE SMARTCOFFEE_BEATRIZ

