CREATE DATABASE oficina_beatriz_barros;
USE oficina_beatriz_barros;

-- TABELAS

CREATE TABLE CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (50) NOT NULL,
CNH INT (9) NOT NULL,
VEICULO VARCHAR (20) NOT NULL,
DATA_ENTREGA DATETIME NOT NULL,
CPF VARCHAR (15),
DATA_RETIRADA DATETIME
);


CREATE TABLE SERVICOS (
ID_SERVICOS INT AUTO_INCREMENT PRIMARY KEY,
TIPO_SERVICO VARCHAR (50) NOT NULL,
VALOR_SERVICO INT (5) NOT NULL,
QUANTIDADE INT (5) NOT NULL,
DATA_INICIO DATETIME NOT NULL, 
DATA_ENTREGA DATETIME
);

CREATE TABLE PAGAMENTOS (
ID_PAGAMENTOS INT AUTO_INCREMENT PRIMARY KEY,
VALOR_FINAL VARCHAR (50) NOT NULL,
FORMA_PAGAMENTO ENUM ("DEBITO", "PIX", "DINHEIRO", "CREDITO") DEFAULT "DINHEIRO",
DESCONTO INT (2) NOT NULL,
SERVICO_PRESTADO VARCHAR (50) NOT NULL, 
COMISSAO_FUNCIONARIO INT (2) NOT NULL
);

